      - name: Upload APK to BrowserStack (Debug)
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        run: |
          echo "Uploading APK to BrowserStack..."
          ls -R apk || echo "APK folder not found!"
          file apk/gsedla_uat_1.0.0_nov_12.apk || echo "APK file not found!"
