      - name: Upload APK to BrowserStack
        id: upload_apk
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        run: |
          echo "Listing APK directory contents:"
          ls -lh apk/

          echo "Uploading APK to BrowserStack..."
          RESPONSE=$(curl -s -w "\nHTTP_STATUS_CODE:%{http_code}\n" -u "$BROWSERSTACK_USERNAME:$BROWSERSTACK_ACCESS_KEY" \
            -X POST "https://api-cloud.browserstack.com/app-automate/upload" \
            -F "file=@apk/gsedla_uat_1.0.0_nov_12.apk")

          echo "$RESPONSE"

          HTTP_STATUS=$(echo "$RESPONSE" | grep HTTP_STATUS_CODE | cut -d ':' -f2 | xargs)
          BODY=$(echo "$RESPONSE" | sed '/HTTP_STATUS_CODE/d')

          if [ "$HTTP_STATUS" -ne 200 ]; then
            echo "❌ APK upload failed with status $HTTP_STATUS"
            echo "Response body: $BODY"
            exit 1
          fi

          APP_URL=$(echo "$BODY" | python3 -c "import sys, json; print(json.load(sys.stdin)['app_url'])")
          echo "✅ APK uploaded successfully: $APP_URL"
          echo "APP_URL=$APP_URL" >> $GITHUB_ENV
