- name: Upload APK to BrowserStack
  id: upload_apk
  env:
    BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
    BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
  run: |
    echo "Uploading APK to BrowserStack..."
    
    RESPONSE=$(curl -s -u "$BROWSERSTACK_USERNAME:$BROWSERSTACK_ACCESS_KEY" \
      -X POST "https://api-cloud.browserstack.com/app-automate/upload" \
      -F "file=@apk/gsedla_uat_1.0.0_nov_12.apk")

    echo "Response: $RESPONSE"

    APP_URL=$(echo "$RESPONSE" | python3 -c "import sys, json; print(json.load(sys.stdin).get('app_url', ''))")

    if [ -z "$APP_URL" ]; then
      echo "APK upload failed or returned no app_url"
      exit 1
    fi

    echo "Upload successful. APP_URL=$APP_URL"
    echo "APP_URL=$APP_URL" >> $GITHUB_ENV
