      - name: Upload APK to BrowserStack
        id: upload_apk
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        run: |
          echo "Uploading APK to BrowserStack..."

          # Upload and capture both response body and status code
          RESPONSE=$(curl -s -u "$BROWSERSTACK_USERNAME:$BROWSERSTACK_ACCESS_KEY" \
            -X POST "https://api-cloud.browserstack.com/app-automate/upload" \
            -F "file=@apk/gsedla_uat_1.0.0_nov_12.apk" -w "\n%{http_code}")

          # Separate response body and status code
          HTTP_BODY=$(echo "$RESPONSE" | sed '$d')
          HTTP_STATUS=$(echo "$RESPONSE" | tail -n1)

          echo "HTTP Status: $HTTP_STATUS"

          if [ "$HTTP_STATUS" -ne 200 ]; then
            echo "APK upload failed with status code $HTTP_STATUS"
            echo "$HTTP_BODY"
            exit 1
          fi

          APP_URL=$(echo "$HTTP_BODY" | python3 -c "import sys, json; print(json.load(sys.stdin).get('app_url', ''))")

          if [ -z "$APP_URL" ]; then
            echo "APK upload failed or returned no app_url"
            echo "$HTTP_BODY"
            exit 1
          fi

          echo "Upload successful. APP_URL=$APP_URL"
          echo "APP_URL=$APP_URL" >> $GITHUB_ENV
